# Generated by Django 5.1.4 on 2025-01-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faceboopages',
            old_name='uri',
            new_name='path_query',
        ),
    ]
