# Generated by Django 5.1.4 on 2025-01-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_uri_faceboopages_path_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_query', models.CharField(max_length=200, unique=True)),
                ('whatsapp', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('website', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='FacebooPages',
        ),
    ]
