# Generated by Django 5.1.4 on 2025-01-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_page_delete_faceboopages'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default="", max_length=30),
            preserve_default=False,
        ),
    ]
