# Generated by Django 5.1.4 on 2025-01-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='instagram',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
