# Generated by Django 5.1.4 on 2025-01-12 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_page_address_alter_page_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Contact',
        ),
    ]
