# Generated by Django 5.1.4 on 2025-01-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contact_not_qualified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='not_qualified',
            field=models.BooleanField(help_text='Account has a website, has been inactive for an extended period, or the page is not found.'),
        ),
    ]
