# Generated by Django 5.1.4 on 2025-01-13 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_decider_alter_contact_not_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='decider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.decider'),
        ),
    ]
