# Generated by Django 5.1.4 on 2025-01-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contact_decider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='path_query',
            new_name='facebook_page',
        ),
    ]
