# Generated by Django 5.1.4 on 2025-01-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='not_qualified',
        ),
        migrations.AddField(
            model_name='contact',
            name='qualified',
            field=models.BooleanField(blank=True, default=None, help_text='Account has a website, has been inactive for an extended period, or the page is not found.', null=True),
        ),
    ]
