# Generated by Django 5.1.4 on 2025-01-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_instagramcontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramcontact',
            old_name='whatsapp',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='instagramcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
