# Generated by Django 5.1.4 on 2025-01-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_whatsapp_instagramcontact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcontact',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
