# Generated by Django 5.1.4 on 2025-01-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_instagramcontact_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True)),
                ('qualified', models.BooleanField(blank=True, default=None, null=True)),
            ],
        ),
    ]
