# Generated by Django 5.1.4 on 2025-01-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
