# Generated by Django 5.1.4 on 2025-01-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_website_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
