# Generated by Django 5.1.4 on 2025-01-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_website_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcontact',
            name='contacted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
