# Generated by Django 5.1.4 on 2025-01-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_instagramcontact_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='linktree',
            field=models.BooleanField(default=False),
        ),
    ]
