# Generated by Django 5.1.4 on 2025-01-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_website_linktree'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='last_post',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
