# Generated by Django 5.1.4 on 2025-01-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_website_last_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='last_post',
        ),
        migrations.AddField(
            model_name='instagramcontact',
            name='last_post',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
