# Generated by Django 5.1.4 on 2025-01-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_instagramcontact_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcontact',
            name='menu',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
