# Generated by Django 5.1.4 on 2025-02-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_instagramcontact_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcontact',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instagramcontact',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
