# Generated by Django 5.1.4 on 2025-02-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_company_vacancycategory_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
