# Generated by Django 5.1.4 on 2025-02-04 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_vacancy_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='message',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.template'),
        ),
    ]
