# Generated by Django 5.1.4 on 2025-02-04 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_template_remove_vacancy_message_vacancy_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='categories',
            new_name='category',
        ),
    ]
