# Generated by Django 5.1.4 on 2025-02-04 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_categories_vacancy_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to=None)),
            ],
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='curriculum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curriculum'),
        ),
    ]
