# Generated by Django 5.1.4 on 2025-02-04 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_curriculum_alter_vacancy_name_vacancy_curriculum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.curriculum'),
        ),
    ]
