# Generated by Django 5.1.4 on 2025-02-04 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_vacancy_curriculum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='archive',
            new_name='archived',
        ),
    ]
