# Generated by Django 5.1.4 on 2025-02-05 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_archive_vacancy_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vacancylevel'),
        ),
    ]
