# Generated by Django 5.1.4 on 2025-02-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_linkedincontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedincontact',
            name='contacted',
        ),
        migrations.RemoveField(
            model_name='linkedincontact',
            name='qualified',
        ),
    ]
