# Generated by Django 5.1.4 on 2025-02-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_linkedincontact_contacted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedincontact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='linkedincontact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='linkedincontact',
            name='phone',
        ),
    ]
