# Generated by Django 5.1.4 on 2025-02-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_linkedincontact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
