# Generated by Django 5.1.4 on 2025-02-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_company_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='qualified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
