# Generated by Django 5.1.4 on 2025-02-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_company_contacted_company_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
