# Generated by Django 5.1.4 on 2025-02-07 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_company_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.template'),
        ),
    ]
