# Generated by Django 5.1.4 on 2025-02-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_company_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='bitly',
            field=models.BooleanField(default=False),
        ),
    ]
