# Generated by Django 5.1.4 on 2025-02-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_website_bitly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instagramcontact',
            old_name='phone',
            new_name='cellphone',
        ),
        migrations.AddField(
            model_name='instagramcontact',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
