# Generated by Django 5.1.4 on 2025-02-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_website_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcontact',
            name='website2',
            field=models.URLField(blank=True, null=True),
        ),
    ]
