# Generated by Django 5.1.4 on 2025-02-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_instagramcontact_website2'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramcontact',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.template'),
        ),
    ]
