# Generated by Django 5.1.4 on 2025-02-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_instagramcontact_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='message',
            field=models.TextField(blank=True, max_length=1200, null=True),
        ),
    ]
