# Generated by Django 5.1.4 on 2025-02-28 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_template_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('cellphone', models.CharField(blank=True, max_length=13, null=True)),
                ('telephone', models.CharField(blank=True, max_length=12, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('website2', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('qualified', models.BooleanField(blank=True, default=None, help_text='Account has a website, has been inactive for an extended period, or the page is not found.', null=True)),
                ('contacted', models.BooleanField(default=False)),
                ('last_post', models.DateTimeField(blank=True, default=None, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('menu', models.BooleanField(blank=True, default=None, null=True)),
                ('decider', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.decider')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.template')),
            ],
        ),
    ]
