# Generated by Django 5.1.4 on 2025-02-28 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_businesscontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscontact',
            name='decider',
        ),
        migrations.AddField(
            model_name='decider',
            name='business_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businesscontact'),
        ),
    ]
