# Generated by Django 5.1.4 on 2025-02-28 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_businesscontact_decider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decider',
            name='business_contact',
        ),
        migrations.DeleteModel(
            name='BusinessContact',
        ),
    ]
