# Generated by Django 5.1.4 on 2025-02-28 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_remove_decider_business_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstagramContact',
            new_name='BusinessContact',
        ),
    ]
