# Generated by Django 5.1.4 on 2025-02-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_rename_instagramcontact_businesscontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='decider',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='businesscontact',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.template'),
        ),
    ]
