# Generated by Django 5.1.4 on 2025-02-28 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_decider_address_alter_businesscontact_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationalVariantPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('background_color', models.CharField(max_length=6)),
                ('text_color', models.CharField(max_length=6)),
                ('font_family', models.CharField(max_length=200)),
                ('font_size', models.PositiveSmallIntegerField(default=64)),
                ('square_area', models.PositiveSmallIntegerField(default=1080)),
                ('text_wrap', models.PositiveSmallIntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='MotivationalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=150)),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.motivationalvariantpost')),
            ],
        ),
    ]
