# Generated by Django 5.1.4 on 2025-02-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_motivationalvariantpost_motivationalpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationalpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
