# Generated by Django 5.1.4 on 2025-03-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_motivationalpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationalpost',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
