# Generated by Django 5.1.4 on 2025-03-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_motivationalpost_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationalpost',
            name='left_background_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='motivationalpost',
            name='right_background_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
