# Generated by Django 5.1.4 on 2025-03-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_motivationalpost_left_background_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motivationalpost',
            old_name='left_background_image',
            new_name='background_image1',
        ),
        migrations.RenameField(
            model_name='motivationalpost',
            old_name='right_background_image',
            new_name='background_image2',
        ),
    ]
