# Generated by Django 5.1.4 on 2025-03-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_rename_left_background_image_motivationalpost_background_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='motivationalpost',
            name='phrase',
            field=models.TextField(max_length=150),
        ),
    ]
