# Generated by Django 5.1.4 on 2025-03-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_hashtag_alter_motivationalpost_phrase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MotivationalPost',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='MotivationalVariantPost',
            new_name='VariantPost',
        ),
    ]
