# Generated by Django 5.1.4 on 2025-03-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_rename_variantpost_postvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hashtag'),
        ),
    ]
