# Generated by Django 5.1.4 on 2025-03-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_post_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
