# Generated by Django 5.1.4 on 2025-03-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_posttype_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='decider',
            name='followed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
