# Generated by Django 5.1.4 on 2025-03-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_decider_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontact',
            name='followed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='decider',
            name='followed',
            field=models.BooleanField(default=False),
        ),
    ]
