# Generated by Django 5.1.4 on 2025-03-04 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_postgenerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgenerator',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.postvariant'),
        ),
    ]
