# Generated by Django 5.1.4 on 2025-03-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_postgenerator_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgenerator',
            name='phrases',
            field=models.TextField(max_length=1500),
        ),
    ]
