# Generated by Django 5.1.4 on 2025-03-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_postgenerator_phrases'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSVG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1500)),
            ],
        ),
    ]
