# Generated by Django 5.1.4 on 2025-03-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_postsvg'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsvg',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
