# Generated by Django 5.1.4 on 2025-03-04 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_postsvg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvariant',
            name='svg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.postsvg'),
        ),
    ]
