# Generated by Django 5.1.4 on 2025-03-04 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_remove_postvariant_svg_post_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgenerator',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='postgenerator',
            name='type',
        ),
        migrations.RemoveField(
            model_name='postgenerator',
            name='variant',
        ),
    ]
