# Generated by Django 5.1.4 on 2025-03-05 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_remove_postgenerator_hashtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vacancylevel'),
        ),
    ]
