# Generated by Django 5.1.4 on 2025-03-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_remove_vacancy_link_vacancy_job_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='job_view',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
