# Generated by Django 5.1.4 on 2025-03-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_alter_vacancy_job_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvariant',
            name='font_family',
        ),
        migrations.RemoveField(
            model_name='postvariant',
            name='font_size',
        ),
        migrations.RemoveField(
            model_name='postvariant',
            name='square_area',
        ),
        migrations.RemoveField(
            model_name='postvariant',
            name='text_wrap',
        ),
        migrations.AddField(
            model_name='post',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=64),
        ),
        migrations.AddField(
            model_name='post',
            name='square_area',
            field=models.PositiveSmallIntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='post',
            name='text_wrap',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='postvariant',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
