# Generated by Django 5.1.4 on 2025-03-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_remove_postvariant_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvariant',
            name='font_family',
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
