# Generated by Django 5.1.4 on 2025-03-12 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_postvariant_font_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgenerator',
            name='generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postgenerator',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.postvariant'),
        ),
    ]
