# Generated by Django 5.1.4 on 2025-03-12 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_postgenerator_generated_postgenerator_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgenerator',
            name='variant',
        ),
        migrations.AddField(
            model_name='postgenerator',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.posttype'),
        ),
    ]
