# Generated by Django 5.1.4 on 2025-03-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_rename_square_area_post_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.PositiveSmallIntegerField(default=1080),
        ),
    ]
