# Generated by Django 5.1.4 on 2025-03-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_duration',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
