# Generated by Django 5.1.4 on 2025-03-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_post_video_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='background_image1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='background_image2',
            new_name='image2',
        ),
    ]
