# Generated by Django 5.1.4 on 2025-03-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_alter_post_aspect_ratio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='aspect_ratio_image',
            field=models.CharField(blank=True, choices=[('9:16', '9:16'), ('4:5', '4:5'), ('3:4', '3:4'), ('1:1', '1:1')], default='9:16', max_length=4, null=True),
        ),
    ]
