# Generated by Django 5.1.4 on 2025-03-18 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_post_font_size_alter_post_text_wrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='variant',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.postvariant'),
        ),
    ]
