# Generated by Django 5.1.4 on 2025-03-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_postgenerator_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
