# Generated by Django 5.1.4 on 2025-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_post_image1_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decider',
            name='followed',
        ),
        migrations.AddField(
            model_name='decider',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
