# Generated by Django 5.1.4 on 2025-03-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_remove_decider_followed_decider_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontact',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='decider',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
