# Generated by Django 5.1.4 on 2025-03-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_businesscontact_cnpj_decider_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
