# Generated by Django 5.1.4 on 2025-03-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_website_ignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='decider',
            name='color',
            field=models.CharField(blank=True, choices=[('slate', '#64748b'), ('gray', '#6b7280'), ('zinc', '#71717a'), ('neutral', '#737373'), ('stone', '#78716c'), ('red', '#ef4444'), ('orange', '#f97316'), ('amber', '#f59e0b'), ('yellow', '#eab308'), ('lima', '#84cc16'), ('green', '#22c55e'), ('emerald', '#10b981'), ('teal', '#14b8a6'), ('cyan', '#06b6d4'), ('sky', '#0ea5e9'), ('blue', '#3b82f6'), ('indigo', '#6366f1'), ('violet', '#8b5cf6'), ('purple', '#a855f7'), ('fuchsia', '#d946ef'), ('pink', '#ec4899'), ('rose', '#f43f5e')], max_length=9, null=True),
        ),
    ]
