# Generated by Django 5.1.4 on 2025-03-25 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_decider_svg_alter_decider_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decider',
            name='svg',
        ),
    ]
