# Generated by Django 5.1.4 on 2025-03-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_businesscontact_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontact',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
