# Generated by Django 5.1.4 on 2025-04-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_businesscontact_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontact',
            name='custom_color',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
