# Generated by Django 5.1.4 on 2025-04-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_businesscontact_custom_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContactProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Business Contact Interactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.businesscontact',),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='likes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
