# Generated by Django 5.1.4 on 2025-04-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_businesscontactproxy_businesscontact_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontact',
            name='comments',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
