# Generated by Django 5.1.4 on 2025-04-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_businesscontact_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='aspect_ratio_image1',
            field=models.CharField(blank=True, choices=[('16:9', '16:9'), ('9:16', '9:16'), ('5:4', '5:4'), ('4:5', '4:5'), ('4:3', '4:3'), ('3:4', '3:4'), ('1:1', '1:1')], default='16:9', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='aspect_ratio_image2',
            field=models.CharField(blank=True, choices=[('16:9', '16:9'), ('9:16', '9:16'), ('5:4', '5:4'), ('4:5', '4:5'), ('4:3', '4:3'), ('3:4', '3:4'), ('1:1', '1:1')], default='16:9', max_length=4, null=True),
        ),
    ]
