# Generated by Django 5.1.4 on 2025-04-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_alter_post_aspect_ratio_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessContactKaban',
            fields=[
            ],
            options={
                'verbose_name': 'Business Contact Kaban',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.businesscontact',),
        ),
    ]
