# Generated by Django 5.1.4 on 2025-05-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_businesscontactkaban'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontact',
            name='interaction_responses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
