# Generated by Django 5.1.4 on 2025-05-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_businesscontact_interaction_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_qualified', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('max_followed', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('max_interacted', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('max_responded', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('max_contacted', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('contacted', models.ManyToManyField(related_name='contacted_contacts', to='core.businesscontact')),
                ('followed', models.ManyToManyField(related_name='followed_contacts', to='core.businesscontact')),
                ('interacted', models.ManyToManyField(related_name='interacted_contacts', to='core.businesscontact')),
                ('qualified', models.ManyToManyField(related_name='qualified_contacts', to='core.businesscontact')),
                ('responded', models.ManyToManyField(related_name='responded_contacts', to='core.businesscontact')),
            ],
        ),
    ]
