# Generated by Django 5.1.4 on 2025-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_alter_interactionflow_contacted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscontact',
            name='move_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='moved_today',
            field=models.BooleanField(default=False),
        ),
    ]
