# Generated by Django 5.1.4 on 2025-05-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_businesscontact_move_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesscontact',
            name='moved_today',
        ),
    ]
