# Generated by Django 5.1.4 on 2025-05-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_remove_businesscontact_moved_today'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessContactKaban',
        ),
        migrations.DeleteModel(
            name='BusinessContactProxy',
        ),
    ]
