# Generated by Django 5.1.4 on 2025-05-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_delete_businesscontactkaban_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BusinessContact',
            new_name='Business',
        ),
    ]
