# Generated by Django 5.1.4 on 2025-05-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_rename_businesscontact_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessKanban',
            fields=[
            ],
            options={
                'verbose_name': 'Business Kanban',
                'verbose_name_plural': 'Business Kanban',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.business',),
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Business', 'verbose_name_plural': 'Business'},
        ),
    ]
