# Generated by Django 5.1.4 on 2025-05-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_businesskanban_alter_business_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InteractionFlow',
        ),
    ]
