# Generated by Django 5.1.4 on 2025-05-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_delete_interactionflow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='decider',
        ),
        migrations.AddField(
            model_name='business',
            name='deciders',
            field=models.ManyToManyField(blank=True, related_name='deciders', to='core.decider'),
        ),
    ]
