# Generated by Django 5.1.4 on 2025-05-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_remove_business_decider_business_deciders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Decider',
            new_name='StaffMember',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='decider',
            new_name='staff_member',
        ),
        migrations.RemoveField(
            model_name='business',
            name='deciders',
        ),
        migrations.AddField(
            model_name='business',
            name='staff_members',
            field=models.ManyToManyField(blank=True, related_name='staff_member', to='core.staffmember'),
        ),
    ]
