# Generated by Django 5.1.4 on 2025-05-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_rename_decider_staffmember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='observation',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
