# Generated by Django 5.1.4 on 2025-05-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_staffmember_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='color',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='is_trusty',
            field=models.BooleanField(default=False),
        ),
    ]
