# Generated by Django 5.1.4 on 2025-05-14 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_remove_staffmember_color_staffmember_is_trusty'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMemberType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='is_trusty',
            field=models.BooleanField(default=False, verbose_name='trusty'),
        ),
        migrations.AddField(
            model_name='staffmember',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staffmembertype'),
        ),
    ]
