# Generated by Django 5.1.4 on 2025-05-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_staffmembertype_alter_staffmember_is_trusty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='facebook',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='observation',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
