# Generated by Django 5.1.4 on 2025-05-14 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_rename_username_business_instagram_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[(None, 'Not contacted'), ('contacted', 'contacted'), ('no_replay', 'No replay'), ('followed_up', 'Follow up'), ('finish', 'Finish')], max_length=30, null=True)),
                ('contact_via', models.CharField(blank=True, choices=[('whatsapp_message', 'WhatsApp message'), ('whatsapp_call', 'WhatsApp call'), ('instagram_dm', 'Instagram DM'), ('phone_call', 'Phone call'), ('email', 'E-mail')], max_length=30, null=True)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
                ('next_interaction_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('follow_up_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('observation', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='interaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.interaction'),
        ),
    ]
