# Generated by Django 5.1.4 on 2025-05-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_interaction_business_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
