# Generated by Django 5.1.4 on 2025-05-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_alter_interaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interaction',
            name='next_interaction_date',
        ),
    ]
