# Generated by Django 5.1.4 on 2025-05-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_remove_interaction_next_interaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='contact_via',
            field=models.CharField(blank=True, choices=[('whatsapp_call', 'WhatsApp call'), ('phone_call', 'Phone call'), ('instagram_dm', 'Instagram DM'), ('whatsapp_message', 'WhatsApp message'), ('facebook_message', 'Facebook message'), ('email', 'E-mail')], max_length=30, null=True),
        ),
    ]
