# Generated by Django 5.1.4 on 2025-05-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_alter_interaction_contact_via'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='business',
            name='custom_color',
        ),
        migrations.RemoveField(
            model_name='business',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='business',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='business',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='business',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='business',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='business',
            name='interaction_responses',
        ),
        migrations.RemoveField(
            model_name='business',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='business',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='business',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='business',
            name='secondary_color',
        ),
    ]
