# Generated by Django 5.1.4 on 2025-05-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_remove_business_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionContactVia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='contact_via',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='status',
        ),
    ]
