# Generated by Django 5.1.4 on 2025-05-15 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_interactioncontactvia_interactionstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='contact_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.interactioncontactvia'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.interactionstatus'),
        ),
    ]
