# Generated by Django 5.1.4 on 2025-05-16 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_interaction_contact_via_interaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='move_date',
        ),
    ]
