# Generated by Django 5.1.4 on 2025-06-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_remove_business_move_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='followers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='following',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
