# Generated by Django 5.1.4 on 2025-06-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_business_followers_business_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='interaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to='core.interaction'),
        ),
    ]
