# Generated by Django 5.1.4 on 2025-07-10 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_alter_business_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_ref', to='core.business'),
        ),
        migrations.AlterField(
            model_name='business',
            name='interaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_ref', to='core.interaction'),
        ),
    ]
