# Generated by Django 5.1.4 on 2025-07-11 20:07

from django.db import migrations

def forward(apps, schema_editor):
    Business = apps.get_model('core', 'Business') # Book
    Interaction = apps.get_model('core', 'Interaction') # Author
    
    for business in Business.objects.all():
        try:
            interaction_id = business.interaction_id
            interaction = Interaction.objects.get(pk=interaction_id)
            interaction.business = business
            interaction.save()
        except Interaction.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_interaction_business_alter_business_interaction'),
    ]

    operations = [
        migrations.RunPython(forward),
    ]
