# Generated by Django 5.1.4 on 2025-07-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_auto_20250711_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='interaction',
        ),
    ]
