# Generated by Django 5.1.4 on 2025-07-11 21:11

from django.db import migrations

def contacted_field_to_interaction(apps, schema_editor):
    Business = apps.get_model('core', 'Business')
    Interaction = apps.get_model('core', 'Interaction')
    InteractionStatus = apps.get_model('core', 'InteractionStatus')
    interaction_status_contacted = InteractionStatus.objects.filter(name="Contacted").first()
    
    for business in Business.objects.filter(contacted=True):
        try:
            interaction = Interaction.objects.get(business_id=business.id)
        except Interaction.DoesNotExist:
            interaction = Interaction()
            interaction.status_id = interaction_status_contacted.id
            interaction.business = business
            interaction.save()
            

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_remove_business_interaction'),
    ]

    operations = [
        migrations.RunPython(contacted_field_to_interaction),
    ]
