# Generated by Django 5.1.4 on 2025-07-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_auto_20250711_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='contacted',
        ),
    ]
