# Generated by Django 5.1.4 on 2025-07-12 18:03

from django.db import migrations


def add_default_interaction(apps, schema_editor):
    Business = apps.get_model('core', 'Business')
    Interaction = apps.get_model('core', 'Interaction')
    InteractionStatus = apps.get_model('core', 'InteractionStatus')
    
    interaction_business = Interaction.objects.filter(business__isnull=False).values_list("business_id", flat=True)
    not_contacted = InteractionStatus.objects.get(name="Not contacted")
    
    for business in Business.objects.exclude(pk__in=interaction_business):
        interaction = Interaction()
        interaction.status = not_contacted
        interaction.business = business
        interaction.save()
            

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_remove_business_contacted'),
    ]

    operations = [
        migrations.RunPython(add_default_interaction)
    ]
